curl -X POST -H "Content-Type: application/json" -d '{"input_sentence": "བདག་ནི་སྐྱེ་བ་ཐམས་ཅད་དུ། །བསྟན་པ་གསལ་བར་བྱེད་གྱུར་ཅིག །བསྟན་པ་གསལ་བར་མ་ནུས་ནའང་། །བསྟན་པའི་ཁུར་ཆེན་འཁུར་བར་ཤོག །ཁུར་ཆེན་འཁུར་བར་མ་ནུས་ནའང་། །བསྟན་པའི་སེམས་ཁྲལ་བྱེད་པ་དང་། །བསྟན་པ་ཉམས་ཀྱིས་དོགས་པ་ཡིས། །བྱ་ར་ཙམ་ཡང་བྱེད་པར་ཤོག །མཁའ་ཁྱབ་ཕ་མ་ཐམས་ཅད་ཀྱི། །སྡུག་བསྔལ་ཐམས་ཅད་སེལ་བར་ཤོག །སྡུག་བསྔལ་སེལ་བར་མ་ནུས་ནའང་། །སྡུག་གྲོགས་ཙམ་ཡང་བྱེད་པར་ཤོག །", "level_of_explanation": 0, "language": "bo-en", "model": "NO"}' https://dharmamitra.org/api/translation/